// This file is created by egg-ts-helper@1.25.8
// Do not modify this file!!!!!!!!!

import 'egg';
import ExportAnserquestionModel = require('./AnserquestionModel');
import ExportCategoryModel = require('./CategoryModel');
import ExportCityModel = require('./CityModel');
import ExportClassgoryModel = require('./ClassgoryModel');
import ExportClassHotModel = require('./ClassHotModel');
import ExportClassitemsModel = require('./ClassitemsModel');
import ExportClassMealModel = require('./ClassMealModel');
import ExportClassSingleModel = require('./ClassSingleModel');
import ExportCommentsModel = require('./CommentsModel');
import ExportConditionsModel = require('./ConditionsModel');
import ExportCountyModel = require('./CountyModel');
import ExportCourceitemsModel = require('./CourceitemsModel');
import ExportExamguideModel = require('./ExamguideModel');
import ExportMycourceModel = require('./MycourceModel');
import ExportOrderitemsModel = require('./OrderitemsModel');
import ExportOrdersModel = require('./OrdersModel');
import ExportPraiseModel = require('./PraiseModel');
import ExportProvinceModel = require('./ProvinceModel');
import ExportQuestionModel = require('./QuestionModel');
import ExportRegistratioModel = require('./RegistratioModel');
import ExportReplayChildModel = require('./ReplayChildModel');
import ExportReplayParentModel = require('./ReplayParentModel');
import ExportSpeclalltyModel = require('./SpeclalltyModel');
import ExportTeacheritemModel = require('./TeacheritemModel');
import ExportTeacherModel = require('./TeacherModel');
import ExportTownModel = require('./TownModel');
import ExportUsersModel = require('./UsersModel');
import ExportVideoGoodModel = require('./VideoGoodModel');
import ExportAdressVillage = require('./adress/village');
import ExportModelsAnserquestion = require('./AnserquestionModel');
import ExportModelsCategory = require('./models/category');
import ExportModelsCity = require('./models/city');
import ExportModelsClassgory = require('./models/classgory');
import ExportModelsClassitems = require('./models/classitems');
import ExportModelsClassHot = require('./models/class_hot');
import ExportModelsClassMeal = require('./models/class_meal');
import ExportModelsClassSingle = require('./models/class_single');
import ExportModelsComments = require('./CommentsModel');
import ExportModelsCommentsModel = require('./CommentsModel');
import ExportModelsConditions = require('./models/conditions');
import ExportModelsCounty = require('./models/county');
import ExportModelsCourceitems = require('./models/courceitems');
import ExportModelsEvaluation = require('./models/evaluation');
import ExportModelsExamguide = require('./models/examguide');
import ExportModelsMycource = require('./models/mycource');
import ExportModelsOrderitems = require('./models/orderitems');
import ExportModelsOrders = require('./models/orders');
import ExportModelsPraise = require('./PraiseModel');
import ExportModelsProvince = require('./models/province');
import ExportModelsQuestion = require('./models/question');
import ExportModelsRegistratio = require('./models/registratio');
import ExportModelsReplayParentModel = require('./ReplayParentModel');
import ExportModelsReplayChild = require('.../../../app/model/models/ReplayParentModel;
import ExportModelsSpeclallty = require('./models/speclallty');
import ExportModelsTeacher = require('./models/teacher');
import ExportModelsTeacheritem = require('./models/teacheritem');
import ExportModelsTown = require('./models/town');
import ExportModelsUsers = require('./models/users');
import ExportModelsVideoGood = require('./models/video_good');
import ExportModelsVillage = require('./models/village');

declare module 'egg' {
  interface IModel {
    AnserquestionModel: ReturnType<typeof ExportAnserquestionModel>;
    CategoryModel: ReturnType<typeof ExportCategoryModel>;
    CityModel: ReturnType<typeof ExportCityModel>;
    ClassgoryModel: ReturnType<typeof ExportClassgoryModel>;
    ClassHotModel: ReturnType<typeof ExportClassHotModel>;
    ClassitemsModel: ReturnType<typeof ExportClassitemsModel>;
    ClassMealModel: ReturnType<typeof ExportClassMealModel>;
    ClassSingleModel: ReturnType<typeof ExportClassSingleModel>;
    CommentsModel: ReturnType<typeof ExportCommentsModel>;
    ConditionsModel: ReturnType<typeof ExportConditionsModel>;
    CountyModel: ReturnType<typeof ExportCountyModel>;
    CourceitemsModel: ReturnType<typeof ExportCourceitemsModel>;
    ExamguideModel: ReturnType<typeof ExportExamguideModel>;
    MycourceModel: ReturnType<typeof ExportMycourceModel>;
    OrderitemsModel: ReturnType<typeof ExportOrderitemsModel>;
    OrdersModel: ReturnType<typeof ExportOrdersModel>;
    PraiseModel: ReturnType<typeof ExportPraiseModel>;
    ProvinceModel: ReturnType<typeof ExportProvinceModel>;
    QuestionModel: ReturnType<typeof ExportQuestionModel>;
    RegistratioModel: ReturnType<typeof ExportRegistratioModel>;
    ReplayChildModel: ReturnType<typeof ExportReplayChildModel>;
    ReplayParentModel: ReturnType<typeof ExportReplayParentModel>;
    SpeclalltyModel: ReturnType<typeof ExportSpeclalltyModel>;
    TeacheritemModel: ReturnType<typeof ExportTeacheritemModel>;
    TeacherModel: ReturnType<typeof ExportTeacherModel>;
    TownModel: ReturnType<typeof ExportTownModel>;
    UsersModel: ReturnType<typeof ExportUsersModel>;
    VideoGoodModel: ReturnType<typeof ExportVideoGoodModel>;
    Adress: {
      Village: ReturnType<typeof ExportAdressVillage>;
    }
    Models: {
      Anserquestion: ReturnType<typeof ExportModelsAnserquestion>;
      Category: ReturnType<typeof ExportModelsCategory>;
      City: ReturnType<typeof ExportModelsCity>;
      Classgory: ReturnType<typeof ExportModelsClassgory>;
      Classitems: ReturnType<typeof ExportModelsClassitems>;
      ClassHot: ReturnType<typeof ExportModelsClassHot>;
      ClassMeal: ReturnType<typeof ExportModelsClassMeal>;
      ClassSingle: ReturnType<typeof ExportModelsClassSingle>;
      Comments: ReturnType<typeof ExportModelsComments>;
      CommentsModel: ReturnType<typeof ExportModelsCommentsModel>;
      Conditions: ReturnType<typeof ExportModelsConditions>;
      County: ReturnType<typeof ExportModelsCounty>;
      Courceitems: ReturnType<typeof ExportModelsCourceitems>;
      Evaluation: ReturnType<typeof ExportModelsEvaluation>;
      Examguide: ReturnType<typeof ExportModelsExamguide>;
      Mycource: ReturnType<typeof ExportModelsMycource>;
      Orderitems: ReturnType<typeof ExportModelsOrderitems>;
      Orders: ReturnType<typeof ExportModelsOrders>;
      Praise: ReturnType<typeof ExportModelsPraise>;
      Province: ReturnType<typeof ExportModelsProvince>;
      Question: ReturnType<typeof ExportModelsQuestion>;
      Registratio: ReturnType<typeof ExportModelsRegistratio>;
      ReplayParentModel: ReturnType<typeof ExportModelsReplayParentModel>;
      ReplayChild: ReturnType<typeof ExportModelsReplayChild>;
      Speclallty: ReturnType<typeof ExportModelsSpeclallty>;
      Teacher: ReturnType<typeof ExportModelsTeacher>;
      Teacheritem: ReturnType<typeof ExportModelsTeacheritem>;
      Town: ReturnType<typeof ExportModelsTown>;
      Users: ReturnType<typeof ExportModelsUsers>;
      VideoGood: ReturnType<typeof ExportModelsVideoGood>;
      Village: ReturnType<typeof ExportModelsVillage>;
    }
  }
}
